name: flutter_course
description: Google Flutter Course 2023

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.2.0
  flutter_dotenv: ^5.0.2
  flutter_redux: ^0.10.0
  http: ^0.13.6
  json_annotation: ^4.8.0
  redux: ^5.0.0
  rxdart: ^0.27.7
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/currency_converter.png
